use crate::error::{HiveError, Result};
use crate::types::{AgentId, PublicKeyHex, TaskId};
use chrono::{DateTime, Utc};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Cryptographic Keypair wrapper for Swarm Agents
pub struct AgentKeypair {
    pub signing_key: SigningKey,
    pub verifying_key: VerifyingKey,
}

impl AgentKeypair {
    pub fn generate() -> Self {
        let mut csprng = OsRng;
        let signing_key = SigningKey::generate(&mut csprng);
        let verifying_key = signing_key.verifying_key();
        Self {
            signing_key,
            verifying_key,
        }
    }

    pub fn public_key_hex(&self) -> PublicKeyHex {
        hex::encode(self.verifying_key.to_bytes())
    }

    pub fn sign_message(&self, message: &[u8]) -> String {
        let sig: Signature = self.signing_key.sign(message);
        hex::encode(sig.to_bytes())
    }
}

/// Cryptographically verifiable execution receipt generated by a Worker node upon completing a task
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskReceipt {
    pub task_id: TaskId,
    pub worker_id: AgentId,
    pub worker_pubkey: PublicKeyHex,
    pub output_payload: String,
    pub execution_digest: String, // SHA256(task_id + worker + prompt_hash + output_hash + timestamp)
    pub signature: String,        // Ed25519 signature over execution_digest
    pub execution_duration_ms: u64,
    pub completed_at: DateTime<Utc>,
}

impl TaskReceipt {
    pub fn create_and_sign(
        task_id: TaskId,
        worker_id: impl Into<String>,
        keypair: &AgentKeypair,
        input_payload: &str,
        output_payload: impl Into<String>,
        execution_duration_ms: u64,
    ) -> Self {
        let output = output_payload.into();
        let worker = worker_id.into();
        let completed_at = Utc::now();

        // Compute prompt hash and output hash
        let mut prompt_hasher = Sha256::new();
        prompt_hasher.update(input_payload.as_bytes());
        let prompt_hash = hex::encode(prompt_hasher.finalize());

        let mut output_hasher = Sha256::new();
        output_hasher.update(output.as_bytes());
        let output_hash = hex::encode(output_hasher.finalize());

        // Digest formula
        let mut digest_hasher = Sha256::new();
        digest_hasher.update(task_id.as_bytes());
        digest_hasher.update(worker.as_bytes());
        digest_hasher.update(prompt_hash.as_bytes());
        digest_hasher.update(output_hash.as_bytes());
        digest_hasher.update(completed_at.to_rfc3339().as_bytes());
        let digest_bytes = digest_hasher.finalize();
        let execution_digest = hex::encode(digest_bytes);

        // Sign the digest
        let signature = keypair.sign_message(execution_digest.as_bytes());

        Self {
            task_id,
            worker_id: worker,
            worker_pubkey: keypair.public_key_hex(),
            output_payload: output,
            execution_digest,
            signature,
            execution_duration_ms,
            completed_at,
        }
    }

    pub fn verify_signature(&self) -> Result<bool> {
        let pubkey_bytes = hex::decode(&self.worker_pubkey)
            .map_err(|e| HiveError::SignatureError(format!("Invalid pubkey hex: {}", e)))?;
        
        let pubkey_arr: [u8; 32] = pubkey_bytes.as_slice().try_into()
            .map_err(|_| HiveError::SignatureError("Public key must be 32 bytes".to_string()))?;
        
        let verifying_key = VerifyingKey::from_bytes(&pubkey_arr)
            .map_err(|e| HiveError::SignatureError(format!("Invalid verifying key: {}", e)))?;

        let sig_bytes = hex::decode(&self.signature)
            .map_err(|e| HiveError::SignatureError(format!("Invalid signature hex: {}", e)))?;
        
        let sig_arr: [u8; 64] = sig_bytes.as_slice().try_into()
            .map_err(|_| HiveError::SignatureError("Signature must be 64 bytes".to_string()))?;
        
        let signature = Signature::from_bytes(&sig_arr);

        verifying_key
            .verify(self.execution_digest.as_bytes(), &signature)
            .map(|_| true)
            .map_err(|e| HiveError::SignatureError(format!("Ed25519 signature check failed: {}", e)))
    }
}
